#!/usr/bin/env python3
"""Pro pro_1777139808 - File utility. Generated by 梧桐ASI."""
import os, sys, argparse, json, hashlib
from pathlib import Path

def analyze(path):
    p = Path(path)
    if not p.exists():
        return {"error": "not found"}
    if p.is_file():
        with open(p, 'rb') as f:
            data = f.read()
        return {
            "name": p.name, "size": len(data), "hash": hashlib.md5(data).hexdigest(),
            "lines": len(data.splitlines())
        }
    results = []
    for f in sorted(p.rglob('*'))[:100]:
        if f.is_file():
            with open(f, 'rb') as fh:
                d = fh.read()
            results.append({"name": str(f), "size": len(d), "hash": hashlib.md5(d).hexdigest()[:8]})
    return results

if __name__ == '__main__':
    p = argparse.ArgumentParser()
    p.add_argument('path', help='file or dir')
    p.add_argument('--json', action='store_true')
    a = p.parse_args()
    r = analyze(a.path)
    if a.json:
        print(json.dumps(r, indent=2))
    elif isinstance(r, list):
        [print(f"{x['name']}: {x['size']}b {x.get('hash','')}") for x in r[:20]]
    else:
        print(f"{r.get('name','')}: {r.get('size',0)}b hash={r.get('hash','')} lines={r.get('lines',0)}")
